# Generated by Django 3.1.2 on 2020-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='body',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
