# Generated by Django 3.1.2 on 2020-10-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20201018_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='photo',
            field=models.ImageField(upload_to='recipe_photos'),
        ),
    ]
