# Generated by Django 3.1.2 on 2020-10-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20201018_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
