# Generated by Django 3.1.2 on 2020-11-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20201023_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
