# Generated by Django 3.1.2 on 2020-11-17 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0007_auto_20201101_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
