# Generated by Django 3.1.2 on 2020-11-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_recipepost_users_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='users_like',
        ),
    ]
