# Generated by Django 3.1.2 on 2020-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_auto_20201123_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique_for_date='publish'),
        ),
    ]
